stages:
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository # Cache Maven dependencies
    - target # Cache build outputs

# Test stage
unit_tests:
  stage: test
  image: maven:3.9.9-eclipse-temurin-23
  script:
    - mvn clean test jacoco:report
  artifacts:
    paths:
      - target/surefire-reports
      - target/site/jacoco
    expire_in: 1 week

jacoco_coverage:
  stage: test
  image: maven:3.9.9-eclipse-temurin-23
  script:
    - mvn -Pjacoco test jacoco:report
  artifacts:
    paths:
      - target/site/jacoco
    expire_in: 1 week
  only:
    - master
    - develop
    - merge_requests
