stages:
  - test
  - e2e

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository # Cache Maven dependencies
    - target # Cache build outputs

# Test stage
unit_tests:
  stage: test
  image: maven:3.9.9-eclipse-temurin-23
  script:
    - mvn clean test jacoco:report
  artifacts:
    paths:
      - target/surefire-reports
      - target/site/jacoco
    expire_in: 1 week

jacoco_coverage:
  stage: test
  image: maven:3.9.9-eclipse-temurin-23
  script:
    - mvn -Pjacoco test jacoco:report
  artifacts:
    paths:
      - target/site/jacoco
    expire_in: 1 week
  only:
    - master
    - develop
    - merge_requests

e2e_tests:
  stage: e2e
  image: postman/newman:alpine
  script:
    # 2a) Install Python (Alpine-based)
    - apk update && apk add python3
    # 2b) Run your Python script first
    - python3 src/main/resources/request.py
    # 2c) Execute Postman e2e tests using Newman
    - newman run src/main/resources/dei.postman_collection.json \
      --reporters cli,junit \
      --reporter-junit-export newman/report.xml
  artifacts:
    paths:
      - newman/report.xml
    expire_in: 1 week
